ViewModels/DashboardViewModel.cs
using System.Collections.Generic;
using RoleTopMvc.Models;
using RoleTopMvc.Repositories;

namespace RoleTopMvc.ViewModels
{
    public class DashboardViewModel : BaseViewModel
    {
        public List<Orcamento> Orcamento {get;set;}
        public uint PedidosAprovados {get;set;}
        public uint PedidosReprovados {get;set;}
        public uint PedidosPendentes {get;set;}

        public DashboardViewModel()
        {
            this.Orcamento = new List<Orcamento>();
        }
    }        
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RoleTopMvc.Models;
using RoleTopMvc.Repositories;
using RoleTopMvc.ViewModels;

namespace RoleTopMvc.Controllers
{
    public class AdministradorController : AbstractController
    {
        OrcamentoRepository orcamentorepository = new OrcamentoRepository();
        
            OrcamentoRepository pedidoRepository = new OrcamentoRepository();
        public IActionResult Dashboard()
        {
            
            DashboardViewModel dashboardViewModel = new DashboardViewModel();
            
            
            dashboardViewModel.NomeView = "Dashboard";
            dashboardViewModel.UsuarioEmail = ObterUsuarioSession();

            return View(dashboardViewModel);
        
        } 


    }
}

Views/Administrador/Dashboard.cshtml
<link href="~/css/cadastro.css" rel="stylesheet" type="text/css">
        <main>
            <form method="POST" action='@Url.Action("Dashboard", "Administrador")'></form>
            <table>
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Tipo de Evento</th>
                        <th>Data</th>
                        <th colspan="2">Aprovar</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Fulaninho da Silva</td>
                        <td>Showzão</td>
                        <td>26/09/2019</td>
                        <td><button>S</button></td>
                        <td><button>N</button></td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Fulaninho da Silva</td>
                        <td>Showzão</td>
                        <td>25/09/2019</td>
                        <td><button>S</button></td>
                        <td><button>N</button></td>
                    </tr>
                </tbody>
            </table>


            <form method="POST" action='@Url.Action("Index", "Home")'>
                <input id="sair" type="submit" value="Sair">
            </form>


        </main>


    